id = "liss-lang"
name = "LISS Language"
version = "0.0.1"
schema_version = 1
authors = ["osdrv"]
description = "LISS language support for Zed."
repository = "https://github.com/osdrv/zed-extension-liss.git"

[grammars.liss]
repository = "https://github.com/osdrv/tree-sitter-liss"
commit = "392e2680b3e98efdf9738a3377a92c4bb961e3e3"
