id = "liss-lang"
name = "LISS Language"
version = "0.0.1"
schema_version = 1
authors = ["osdrv"]
description = "LISS language support for Zed."
repository = "https://github.com/osdrv/zed-extension-liss.git"

[grammars.liss]
repository = "https://github.com/osdrv/tree-sitter-liss"
commit = "4a91e9876fb8d331c08e582f86c9cf4a74870c38"
